module.exports = [
  { id: 1,
    name: 'Sói 100%',
    img: 'img/films/1.jpg',
    name_en: '100% Wolf',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Săn cá mập',
    img: 'img/films/2.jpg',
    name_en: 'Shark Lake',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Đứa con của thời tiết',
    img: 'img/films/3.jpg',
    name_en: 'Weathering With You',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Cậu bé Artemis Fowl',
    img: 'img/films/4.jpg',
    name_en: 'Artemis Fowl',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Vụ án con mèo mất tích',
    img: 'img/films/5.jpg',
    name_en: 'A Case Of A Missing Cat',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Bầu trời xanh trong mắt em',
    img: 'img/films/6.jpg',
    name_en: 'Her Blue Sky',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Sở thú thoát ế',
    img: 'img/films/7.jpg',
    name_en: 'Secret Zoo',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Cậu bé ma 2',
    img: 'img/films/8.jpg',
    name_en: 'Brahms: The Boy II',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Bê bối tình dục thể dục dụng cụ Mỹ',
    img: 'img/films/9.jpg',
    name_en: 'Athlete A',
    time: '85 phút',
    format: 'HD-Vietsub' },

  { id: 1,
    name: 'Sống hai đời, yêu một lần',
    img: 'img/films/10.jpg',
    name_en: 'Live Twice, Love Once',
    time: '85 phút',
    format: 'HD-Vietsub' }
]
